KoKuToru/gTox

Tox/Tox.cpp
Widget/Chat/WidgetChatLabel.cpp
Widget/WidgetChat.cpp

Update settings branch

---

Dialog/DialogContact.cpp
Locale/en.po
Tox/ToxDatabase.cpp
Tox/ToxDatabase.h
Widget/Settings/WidgetCache.cpp

Cleanup logs

---

Tox/ToxDatabase.cpp
Tox/ToxDatabase.h
main.cpp

Tox sts data directory

---

CMakeLists.txt
Dialog/DialogProfile.cpp
Dialog/DialogProfile.h
Locale/de.po
Locale/en.po
main.cpp

Tox sts user profiles

---

CMakeLists.txt
Dialog/DialogChat.cpp
Dialog/DialogContact.cpp
Dialog/DialogContact.h
Helper/ToxEventCallback.cpp
Helper/ToxEventCallback.h
Tox/Tox.cpp
Tox/Tox.h
Tox/ToxEvent.cpp
Tox/ToxEvent.h
Widget/WidgetChat.cpp
Widget/WidgetContactListItem.cpp
Widget/WidgetContactListItem.h

I think thats more C++ like,
plus better support for custom events.

New ToxEvent

---

src/CMakeLists.txt
src/i18n/CMakeLists.txt
src/main.cpp

If this looks good but needs modifications I'll make them tomorrow. Well, later today technically.
Ok, I've unmessed this up and closed #143.

Re written translation buliding and modification to translation initialisation code

---

.travis.yml
src/tox/test/contact.t.h

Enable test

---

.travis.yml
Dockerfile

Prebuild docker image to improve travis build time

Use kokutoru/gtox-travis-build docker image

---

.travis.yml

Add a test mode which is allowed to fail.
build-status shouldn't depend on test.
(This is my personal opinion)

Build matrix

---

src/tox/core.cpp
src/tox/core.h

This will improve connection time a lot !
Hardcoded for now.
Randomly select 5 nodes every 5 seconds until connected.
Then select 1 node every 60 seconds.

Add bootstrap node list

---

src/dialog/main.cpp
src/i18n/en.po
src/resources/ui/status_menu.ui

Added a menu entry into the status change menu.
Implements #138

Implement a way of chaning profile without restarting

---

src/tox/profile.cpp

Should make gtox useable on windows

WIN-HACK: remove old profile before renaming the new profile

---

src/tox/profile.cpp
src/tox/profile.h
src/tox/test/profile.t.h

use Gio::File in toxmm::profile

---

src/i18n/CMakeLists.txt
src/i18n/fr.po

This pull-request add french translations.

Added french translation

---

src/i18n/ru.po

This PR adds complete russian translation to the project.

Russian translation

---

src/i18n/de.po

I fixed as much as I found. There may still be some clumsy phrasing.

Fixed German translation

---

src/config.cpp
src/config.h
src/dialog/main.cpp
src/dialog/main.h
src/dialog/settings.cpp
src/resources/flatbuffers/ConfigGlobal.fbs
src/resources/ui/dialog_settings.ui
src/tox/CMakeLists.txt
src/tox/config.cpp
src/tox/config.h
src/tox/contact/contact.cpp
src/tox/contact/file/manager.cpp
src/tox/core.cpp
src/tox/core.h
src/tox/flatbuffers/CMakeLists.txt
src/tox/flatbuffers/Config.fbs
src/tox/test/global_fixture.t.h

Enable network settings options.
for #180

network settings

---

src/tox/contact/contact.cpp
src/tox/contact/contact.h
src/tox/contact/manager.cpp
src/tox/contact/manager.h
src/tox/core.cpp
src/tox/test/contact.t.h

use `std::string` or `glib::ustring::bytes()`
fix #187

Glib::ustring::size() is 99% of the time not what you want.

---

src/dialog/chat.cpp
src/dialog/chat.h
src/tox/contact/file/file.cpp
src/tox/contact/file/file_recv.cpp
src/tox/contact/file/manager.cpp
src/widget/chat_file.cpp
src/widget/chat_file.h
src/widget/contact.cpp

Auto accept

---

src/dialog/detachable_window.cpp
src/dialog/detachable_window.h
src/widget/contact.cpp

stop contact spinner when chat is active

---

src/i18n/de.po
src/i18n/en.po
src/i18n/es.po
src/i18n/fr.po
src/i18n/ru.po
src/utils/gstreamer.cpp

Fix writing error in the english translation
